### ISSUE TITLE
Problem with PDF image rendering/extraction on windows

### ISSUE THREAD

**Issue by b2m** [JKamlah/tesseractXplore#12]
Environment: Windows 10 with tesseractXplore **V0.2.2**

In tesseractXplore I want to extract images from my PDF files to be able to perform OCR on them.

The following transitions are regularly successful:

 - PDF => rendering => jpg | png
 - PDF => extraction => png | ppm

The following transitions yield empty files:

 - PDF => rendering => tiff
 - PDF => extraction => tiff

The following transitions yield no files:

 - PDF => rendering => jp2 | ppm
 - PDF => extraction => jp2 | jpeg

**Comment by JKamlah** [comment]
The problem with creating tif on windows is due to a problem with the libtiff libary. Here is a newer prebuilt-binaries source which don't have the problem. https://github.com/oschwartz10612/poppler-windows/releases/tag/v21.03.0  Do you think this is trustworthy source?

**Comment by b2m** [comment]
> Do you think this is trustworthy source?

Owen Schwartz is using GitHub Actions to repackage https://anaconda.org/conda-forge/poppler into a standalone windows package. So the original source (anaconda) is quite trustworthy, the process seems ok.

**Comment by JKamlah** [comment]
I think so too.
