### ISSUE TITLE
Load data from other disks on Windows

### ISSUE THREAD

**Issue by b2m** [JKamlah/tesseractXplore#14]
Environment: Windows 10 with tesseractXplore **V0.2.2**

On Windows it is not possible with tesseractXplore to access data on an usb drive, network drive or different hard drive.

**Comment by JKamlah** [comment]
I am still searching with some results for at least external hard and usb drives.

**Comment by JKamlah** [comment]
I have implemented the option to insert a path manually, which seems to work perfect.
