### ISSUE TITLE
Not an issue but a request

### ISSUE THREAD

**Issue by johnlockejrr** [JKamlah/tesseractXplore#18]
Sorry to make this as an issue but couldn't find other way to contact you.
I try to install and test eScriptorium with tesseract as per https://ub-mannheim.github.io/eScriptorium_Dokumentation/eScriptorium-with-tesseract-extension.html
But when trying to clone the modified eScriptorium with `git clone https://github.com/JKamlah/eScriptorium/ -b extension-tesseract --single-branch` weems the repo doesn't wxist anymore, can I have it somehow? Thank you so much!

**Comment by JKamlah** [comment]
Hello @johnlockejrr,
i apologize for the oversight; the repository was still set to private but has now been made public, allowing you to clone it without issues. For the Tesseract engine to function in eScriptorium, you will need to install both Tesseract and TesserOCR (https://github.com/sirfz/tesserocr).

While the code is operational, there are a few key points to note. If your intention is simply to run the code on a local machine, utilizing existing Tesseract models for transcription with a pre-existing layout (either through Kraken models or by uploading your own), you should encounter no difficulties. However, if you're looking to use eScriptorium for Tesseract model training, a specialized version of Tesseract and TesserOCR is required, for which I can provide links, and you can only run it in a synchronous state. We are considering a revision in the method used to train Tesseract within eScriptorium. 
Ben Silverman is currently making significant contributions to eScriptorium's development and internal function calls. We have decided to delay adapting our Tesseract integration until after the completion of these major changes. Although we have a functional version for both transcription and training with Tesseract in eScriptorium, it still requires further refinement and i personally wouldn't recommend to use it in the current state for training. Therefore, I would advise waiting a few more months until we have refined our method to a point where it is ready for widespread use. We plan to start the rework in summer this year.

**Comment by johnlockejrr** [comment]
Thank you so much!
